
name: CI Pytest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [macos-latest, windows-latest, ubuntu-latest]
            python-version: ['3.9', '3.8']
            exclude:
              - os: ubuntu-latest
                python-version: '3.9'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
    - name: Run and write pytest
      run: |
        pytest --cov=spacy_wrap --cov-report term-missing

  pytest-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4.3.0
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
    - name: Run and write pytest
      run: |
        set -o pipefail
        pytest --cov=spacy_wrap --cov-report term-missing | tee pytest-coverage.txt

    - name: Pytest coverage comment
      if: ${{ github.event_name == 'push' }}
      id: coverage-comment
      uses: MishaKav/pytest-coverage-comment@v1.1.40
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        github-token: ${{ secrets.SPHINX_DOCUMENTATION }}

    - name: Check the output coverage
      if: ${{ github.event_name == 'push' }}
      run: |
        echo "Coverage Report - ${{ steps.coverage-comment.outputs.coverage }}"
        echo "Coverage Color - ${{ steps.coverage-comment.outputs.color }}"

    - name: Create the Badge
      if: ${{ github.event_name == 'push' }}
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.PYTEST_COVERAGE }}
        gistID: 33fb85a2c440013df494c1fce884633c
        filename: badge-spacy-wrap-coverage.json
        label: Coverage
        message: ${{ steps.coverage-comment.outputs.coverage }}
        color: ${{ steps.coverage-comment.outputs.color }}
        namedLogo: python
